name: Trigger GitLab Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab CI/CD Deployment Pipeline
        run: |
          curl -X POST \
            -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} \
            -F ref=main \
            https://gitlab.com/api/v4/projects/67382971/trigger/pipeline
